# http://www.appveyor.com/docs/appveyor-yml

# configuration for "master" branch
-
  branches:
    only:
      - master

  version: "{build}"

  environment:
    MSBUILD_FILE_VERBOSITY: detailed
    CI: true

  install:
    - choco install scriptcs

  build_script:
    - C:\Users\appveyor\AppData\Local\scriptcs\scriptcs.exe baufile.csx

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
  artifacts:
    - path: artifacts\output\*.nupkg
      name: nugetpackage
    - path: artifacts\logs
    - path: artifacts\tests

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# provider names are case-sensitive!
  deploy:
    # Deploying to NuGet feed
    - provider: NuGet
      api_key:
        secure: xW5RqeSB/bCnN2QC0d4rcmmQkxUwfpeRtMxUMA22JYaAf89OSaKZNUsmmxrw9S6Z
      artifact: nugetpackage

# configuration for all other branches
-
  version: "{build}"

  environment:
    MSBUILD_FILE_VERBOSITY: detailed
    CI: true

  install:
    - choco install scriptcs

  build_script:
    - set VERSION_SUFFIX=.%APPVEYOR_BUILD_NUMBER%-dev
    - C:\Users\appveyor\AppData\Local\scriptcs\scriptcs.exe baufile.csx

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
  artifacts:
    - path: artifacts\output\*.nupkg
      name: mygetpackage
    - path: artifacts\logs
    - path: artifacts\tests

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# provider names are case-sensitive!
  deploy:
    # Deploying to myget feed
    - provider: NuGet
      server: https://www.myget.org/F/coloredconsole/
      api_key:
        secure: TXdo8W04gLRJunta/6a+cpvXQp6Oq69M6Sk4q94qZ6rnoRkwMYG4O73XiJrsZf5I
      artifact: mygetpackage
